// WARNING! this code was generated by a tool

using Slox.Scanning;

#nullable enable

namespace Slox.Syntax;

public abstract record Expr
{

    public record Binary(Expr Left, Token Operator, Expr Right) : Expr();
    public record Grouping(Expr Expression) : Expr();
    public record Literal(object? Value) : Expr();
    public record Unary(Token Operator, Expr Right) : Expr();

}
